version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
      - PORT=5001
      - MONGO_URI=mongodb://mongo:27017/uo_compagnon # Écrase la valeur localhost de .env
      - JWT_SECRET=supersecret_dev_key_only
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017" # Utile si tu veux te connecter avec MongoDB Compass
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
